version: '3.9'
services:
  nestapp:
    container_name: nestjs
    image: mradul/nestjs:1.0.0
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB_TYPE=postgres
      - PG_HOST=database-1.cn2sye8sqbq4.eu-north-1.rds.amazonaws.com 
      - PG_USER=mradulsinghpost
      - PG_PASSWORD=ZXFangtMfoKLRDlMwXYd
      - PG_DB=database-1
      - PG_PORT=5432
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}